### ISSUE TITLE
[18:45:15 WARN]: [io.javalin.Javalin] Uncaught exception

### ISSUE THREAD

**Issue by hed516** [servertap-io/servertap#244]
[18:45:15 WARN]: [io.javalin.Javalin] Uncaught exception
java.lang.NullPointerException: Cannot read the array length because the return value of "com.mojang.authlib.yggdrasil.response.ProfileSearchResultsResponse.getProfiles()" is null
        at com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository.findProfilesByNames(YggdrasilGameProfileRepository.java:59) ~[paper-1.19.4.jar:?]
        at com.destroystokyo.paper.profile.PaperGameProfileRepository.findProfilesByNames(PaperGameProfileRepository.java:44) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.server.players.GameProfileCache.lookupGameProfile(GameProfileCache.java:110) ~[?:?]
        at net.minecraft.server.players.GameProfileCache.get(GameProfileCache.java:181) ~[?:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftProfileBanList.getProfile(CraftProfileBanList.java:107) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftProfileBanList.isBanned(CraftProfileBanList.java:82) ~[paper-1.19.4.jar:git-Paper-550]
        at org.bukkit.craftbukkit.v1_19_R3.CraftOfflinePlayer.isBanned(CraftOfflinePlayer.java:112) ~[paper-1.19.4.jar:git-Paper-550]
        at io.servertap.api.v1.PlayerApi.offlinePlayersGet(PlayerApi.java:147) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.http.servlet.DefaultTasks.HTTP$lambda-8$lambda-6$lambda-5$lambda-4$lambda-3(DefaultTasks.kt:32) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.http.servlet.JavalinServlet.handleTask(JavalinServlet.kt:88) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.http.servlet.JavalinServlet.handleSync(JavalinServlet.kt:53) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.http.servlet.JavalinServlet.service(JavalinServlet.kt:41) ~[ServerTap-0.5.3.jar:?]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.jetty.JavalinJettyServlet.service(JavalinJettyServlet.kt:58) ~[ServerTap-0.5.3.jar:?]
        at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:587) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:529) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1570) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:221) ~[ServerTap-0.5.3.jar:?]
        at io.javalin.jetty.JettyServer$start$wsAndHttpHandler$1.doHandle(JettyServer.kt:57) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:176) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:484) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1543) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:174) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1304) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:129) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.Server.handle(Server.java:563) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:505) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:762) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:497) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:282) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:314) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.runTask(AdaptiveExecutionStrategy.java:416) ~[ServerTap-0.5.3.jar:?]
        at org.eclipse.jetty.util.thread.strategy.AdaptiveExecutionStrategy.consumeTask(AdaptiveExecutionStrategy.java:385)

**Comment by srmullaney** [comment]
@hed516 Can you open an issue in our discord? It will be easier to support you there.
