### ISSUE TITLE
Could not pass event PlayerQuitEvent to ServerTap v0.6.1

### ISSUE THREAD

**Issue by EaryTide** [servertap-io/servertap#266]
Hello Community, 

i get this Error everytime someone Joins or Leaves the Server and i dont understand it. Can someone explain to me whats happening and how to fix it?

```
[11:17:38 INFO]: EaryTide lost connection: Disconnected
[11:17:38 ERROR]: Could not pass event PlayerQuitEvent to ServerTap v0.6.1
java.lang.ClassCastException: class com.destroystokyo.paper.profile.CraftPlayerProfile cannot be cast to class org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile (com.destroystokyo.paper.profile.CraftPlayerProfile and org.bukkit.craftbukkit.v1_20_R1.profile.CraftPlayerProfile are in unnamed module of loader java.net.URLClassLoader @675d3402)
	at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:79) ~[paper-1.20.1.jar:git-Paper-70]
	at org.bukkit.craftbukkit.v1_20_R1.ban.CraftProfileBanList.isBanned(CraftProfileBanList.java:17) ~[paper-1.20.1.jar:git-Paper-70]
	at org.bukkit.craftbukkit.v1_20_R1.entity.CraftPlayer.isBanned(CraftPlayer.java:1631) ~[paper-1.20.1.jar:git-Paper-70]
	at io.servertap.webhooks.WebhookEventListener.fromBukkitPlayer(WebhookEventListener.java:196) ~[ServerTap-0.6.1.jar:?]
	at io.servertap.webhooks.WebhookEventListener.onPlayerQuit(WebhookEventListener.java:122) ~[ServerTap-0.6.1.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor61.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:git-Paper-70]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.1.jar:git-Paper-70]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[paper-1.20.1.jar:git-Paper-70]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:615) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:599) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.players.PlayerList.remove(PlayerList.java:584) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2123) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2102) ~[?:?]
	at net.minecraft.network.Connection.handleDisconnection(Connection.java:818) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1587) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-70]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-70]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by phybros** [comment]
What versions of everything are you running (server etc)
